import { createElement } from '@lwc/engine-dom';
import Or_customMaskingCmp from 'c/or_customMaskingCmp';

describe('c-or-custom-masking-cmp', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-or-custom-masking-cmp', {
            is: Or_customMaskingCmp
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});